source 'https://rubygems.org'

gem 'activerecord'
gem 'annotate'
gem 'graphql'
gem 'multi_json'
gem 'pry'
gem 'puma'
gem 'rack-parser'
gem 'rake'
gem 'sinatra'
gem 'sinatra-activerecord'
gem 'sinatra-contrib'
gem 'sqlite3'
